[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200